name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run:
          docker build -t ghcr.io/mrpagex/console/myimg:latest
          docker run ghcr.io/mrpagex/console/myimg:latest
          docker push ghcr.io/mrpagex/console/myimg:latest
          