# name: publish
# on: [push]
# jobs:
#   publish-hello-docker-image:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Build the hello-docker Docker image
#         run:
#           docker build . --tag ghcr.io/mrpagex/myimg:latest
#           docker run ghcr.io/mrpagex/myimg:latest
#           docker push ghcr.io/mrpagex/myimg:latest


name: publish
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_PACKAGES_USER }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Docker Build image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/mrpagex/console:${{ github.sha }}
          docker tag ghcr.io/mrpagex/console:${{ github.sha }} ghcr.io/mrpagex/console:latest

      - name: Docker Push
        run: |
         docker push ghcr.io/mrpagex/console:${{ github.sha }}
         docker push ghcr.io/mrpagex/console:latest
          