name: publish
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          login-server: ghcr.io
          username: ${{ secrets.GH_PACKAGES_USER }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/mrpagex/console:${{ github.sha }}
          docker tag ghcr.io/mrpagex/console:${{ github.sha }} ghcr.io/mrpagex/console:latest

      - uses: docker/container-scan@v0
        with:
          image-name: ghcr.io/mrpagex/console:latest          